---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argoslower
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "argoproj.io"
  verbs:
  - get
  - list
  - watch
  resources:
  - eventsources
- apiGroups:
  - networking.istio.io
  verbs:
  - "*"
  resources:
  - virtualservices
- apiGroups:
  - security.istio.io
  verbs:
  - "*"
  resources:
  - authorizationpolicies
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argoslower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoslower
subjects:
- kind: ServiceAccount
  name: argoslower
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argoslower
  namespace: argo
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list
  - get
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argoslower
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argoslower
subjects:
- kind: ServiceAccount
  name: argoslower
  namespace: argo
