apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: argo-tester-github
  namespace: devops
  annotations:
    v1alpha1.argoslower.kanopy-platform/known-source: "github"
spec:
  eventBusName: tester
  service:
    ports:
    - port: 80
      targetPort: 8080
  github:
    example:
      webhook:
        endpoint: /example
        method: POST
        port: "8080"
      repositories:
        - owner: kanopy-platform
          names:
            - argoslower
      webhookSecret:
        name: argoslower-examples
        key: token
        optional: true
