apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo-day
  namespace: devops
  annotations:
    v1alpha1.argoslower.kanopy-platform/known-source: "thing"
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    example:
      authSecret:
        key: token
        name: demo-day-token
      endpoint: /example
      method: POST
      port: "12000"
      serverCertSecret:
        key: tls.crt
        name: demo-day-cert
      serverKeySecret:
        key: tls.key
        name: demo-day-cert
      url: ""
